# Generated by Django 4.1 on 2022-08-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_avg_rating'),
        ('store', '0011_alter_cartitem_unique_together'),
    ]

    operations = [
    ]
